version: '1.3'
services:
  db:
    image: mysql
    volumes:
      - ./tmp/db:/var/lib/...

  web:
    build: .
    command: bundle exec rails s
    volumes:
      - .:/gps-project
    depends_on:
      - db
